### ISSUE TITLE
Public release of pyseascape

### ISSUE THREAD

**Issue by akaszynski** [pyansys/pyseascape#19]
- [x] GitHub pages documentation 
- [x] Legal paperwork (chain of liability)
- [x] Technical review
- [x] Make public
- [x] Upload package to public PyPI

**Comment by kaleabhip** [comment]
@akaszynski The package has been uploaded to PyPI. The checklist is checked out. Thanks a lot for @MaxJPRey for all the help. Let me know if there is anything else to be done. Otherwise, we can close this issue. 

Thanks for your help as well.

**Comment by MaxJPRey** [comment]
@kaleabhip It was a pleasure to collaborate with you.
 I think we can close this issue now.
